# Application
spring.application.name=sksons-Cultivators-management-system

# Render dynamic port
server.port=${PORT:8080}

# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://deepakpalanivel:Deepak9633@cluster0.6o4ue4m.mongodb.net/sksons_Cultivators?retryWrites=true&w=majority

# Admin credentials
app.admin.username=sksons
app.admin.password=sksons9633

# Logging
logging.level.com.sksons=DEBUG