# Application
spring.application.name=SK SONS Cultivaters Management System
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://deepakpalanivel:Deepak9633@cluster0.6o4ue4m.mongodb.net/sksons_cultivaters?retryWrites=true&w=majority


# Admin Credentials (simple hardcoded auth)
app.admin.username=admin
app.admin.password=admin123

# Logging
logging.level.com.sksons=DEBUG
